#!/usr/bin/env python3
"""
Rerank keyword-based reviewer candidates with the author citation graph.

Input : CSV generated by 03_keyword_filter_auther.py
Graph : author_citation_graph.graphml from 06_build_author_citation_graph.py
Output: CSV with graph features and combined_score

Score:
combined_score = 0.6 * keyword_score_norm + 0.4 * author_graph_score
"""

import argparse
import csv
import math
from collections import defaultdict

import networkx as nx


INPUT_FILE = "prof_lin_recommend_by_sim2.csv"
OUTPUT_FILE = "prof_lin_recommend_with_graph_0.25.csv"
AUTHOR_GRAPH_FILE = "author_citation_graph.graphml"

KEYWORD_WEIGHT = 0.75
GRAPH_WEIGHT = 0.25
DIRECT_WEIGHT_CAP = 10.0
TWO_HOP_SCORE = 0.35
THREE_HOP_SCORE = 0.15


def is_chinese_char(char: str) -> bool:
    return "一" <= char <= "鿿"


def has_chinese(text: str) -> bool:
    return any(is_chinese_char(char) for char in text)


def parse_name_token(token: str) -> tuple[str, str]:
    token = token.strip()
    if not token:
        return ("", "")
    if "=" in token:
        left, _, right = token.partition("=")
        left, right = left.strip(), right.strip()
        if has_chinese(left):
            return (left, right)
        if has_chinese(right):
            return (right, left)
        return (left or right, left or right)
    if has_chinese(token):
        return (token, "")
    return (token, token)


def parse_paper_authors(field: str) -> list[str]:
    authors = []
    seen = set()
    for token in (field or "").split("|"):
        node_id, en_name = parse_name_token(token)
        for name in (node_id, en_name):
            name = name.strip()
            if name and name not in seen:
                seen.add(name)
                authors.append(name)
    return authors


def candidate_name_options(row: dict) -> list[str]:
    names = []
    for value in (row.get("author", ""), row.get("english_name", "")):
        for part in str(value or "").split("/"):
            name = part.strip()
            if name and name not in names:
                names.append(name)
    return names


def first_graph_node(graph: nx.Graph, names: list[str]) -> str:
    for name in names:
        if name in graph:
            return name
    return ""


def direct_graph_score(weight: float) -> float:
    capped = min(max(weight, 0.0), DIRECT_WEIGHT_CAP)
    return 0.6 + 0.4 * (math.log1p(capped) / math.log1p(DIRECT_WEIGHT_CAP))


def score_candidate_against_author(
    graph: nx.Graph,
    candidate_node: str,
    paper_author_node: str,
) -> dict:
    if not candidate_node or not paper_author_node:
        return {
            "score": 0.0,
            "distance": "",
            "weight": "",
            "note": "missing_graph_node",
        }

    if candidate_node == paper_author_node:
        return {
            "score": 1.0,
            "distance": 0,
            "weight": "",
            "note": "same_author",
        }

    if graph.has_edge(candidate_node, paper_author_node):
        weight = float(graph[candidate_node][paper_author_node].get("weight", 1.0))
        return {
            "score": direct_graph_score(weight),
            "distance": 1,
            "weight": weight,
            "note": f"direct_weight={weight:g}",
        }

    lengths = nx.single_source_shortest_path_length(graph, candidate_node, cutoff=3)
    distance = lengths.get(paper_author_node)
    if distance == 2:
        return {
            "score": TWO_HOP_SCORE,
            "distance": 2,
            "weight": "",
            "note": "2_hops",
        }
    if distance == 3:
        return {
            "score": THREE_HOP_SCORE,
            "distance": 3,
            "weight": "",
            "note": "3_hops",
        }

    return {
        "score": 0.0,
        "distance": "",
        "weight": "",
        "note": "no_path_within_3_hops",
    }


def graph_features_for_row(graph: nx.Graph, row: dict) -> dict:
    candidate_node = first_graph_node(graph, candidate_name_options(row))
    paper_author_nodes = [
        node for node in (first_graph_node(graph, [name]) for name in parse_paper_authors(row.get("paper_authors", "")))
        if node
    ]

    if not candidate_node:
        return {
            "candidate_graph_node": "",
            "nearest_paper_author": "",
            "author_graph_score": 0.0,
            "author_graph_distance": "",
            "author_graph_weight": "",
            "graph_relation_note": "candidate_missing_from_graph",
        }
    if not paper_author_nodes:
        return {
            "candidate_graph_node": candidate_node,
            "nearest_paper_author": "",
            "author_graph_score": 0.0,
            "author_graph_distance": "",
            "author_graph_weight": "",
            "graph_relation_note": "paper_authors_missing_from_graph",
        }

    best = None
    for paper_author_node in paper_author_nodes:
        scored = score_candidate_against_author(graph, candidate_node, paper_author_node)
        scored["nearest_paper_author"] = paper_author_node
        if best is None or scored["score"] > best["score"]:
            best = scored

    return {
        "candidate_graph_node": candidate_node,
        "nearest_paper_author": best["nearest_paper_author"],
        "author_graph_score": round(float(best["score"]), 6),
        "author_graph_distance": best["distance"],
        "author_graph_weight": best["weight"],
        "graph_relation_note": best["note"],
    }


def read_rows(path: str) -> list[dict]:
    with open(path, encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        if not reader.fieldnames:
            raise SystemExit(f"{path} 沒有欄位列。")
        return rows, reader.fieldnames


def score_column(row: dict) -> float:
    value = row.get("keyword_score") or row.get("final_score") or 0.0
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def add_scores(rows: list[dict], graph: nx.Graph) -> list[dict]:
    groups = defaultdict(list)
    for index, row in enumerate(rows):
        groups[row.get("source_id", "")].append((index, row))

    output_rows = [None] * len(rows)
    for _, indexed_rows in groups.items():
        keyword_scores = [score_column(row) for _, row in indexed_rows]
        min_score = min(keyword_scores)
        max_score = max(keyword_scores)
        score_range = max_score - min_score

        enriched = []
        for index, row in indexed_rows:
            keyword_score = score_column(row)
            if score_range > 0:
                keyword_score_norm = (keyword_score - min_score) / score_range
            else:
                keyword_score_norm = 1.0

            graph_features = graph_features_for_row(graph, row)
            author_graph_score = float(graph_features["author_graph_score"])
            combined_score = (
                KEYWORD_WEIGHT * keyword_score_norm
                + GRAPH_WEIGHT * author_graph_score
            )

            new_row = dict(row)
            new_row["keyword_score_norm"] = round(float(keyword_score_norm), 6)
            new_row.update(graph_features)
            new_row["combined_score"] = round(float(combined_score), 6)
            enriched.append((index, new_row))

        enriched.sort(
            key=lambda item: (
                -float(item[1]["combined_score"]),
                -float(item[1]["keyword_score_norm"]),
                item[1].get("author", ""),
            )
        )
        for rank, (index, row) in enumerate(enriched, 1):
            row["graph_rerank_rank"] = rank
            output_rows[index] = row

    return [row for row in output_rows if row is not None]


def write_rows(path: str, rows: list[dict], original_fields: list[str]) -> None:
    added_fields = [
        "keyword_score_norm",
        "candidate_graph_node",
        "nearest_paper_author",
        "author_graph_score",
        "author_graph_distance",
        "author_graph_weight",
        "graph_relation_note",
        "combined_score",
        "graph_rerank_rank",
    ]
    fieldnames = list(original_fields)
    for field in added_fields:
        if field not in fieldnames:
            fieldnames.append(field)

    sorted_rows = sorted(
        rows,
        key=lambda row: (
            int(row.get("paper_rank") or 0),
            int(row.get("graph_rerank_rank") or 0),
        )
    )

    with open(path, "w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(sorted_rows)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Rerank 03 keyword recommendations with author_citation_graph.graphml."
    )
    parser.add_argument("input_file", nargs="?", default=INPUT_FILE)
    parser.add_argument("output_file", nargs="?", default=OUTPUT_FILE)
    args = parser.parse_args()

    print(f"Reading recommendations: {args.input_file}")
    rows, fieldnames = read_rows(args.input_file)
    print(f"Rows: {len(rows)}")

    print(f"Reading author graph: {AUTHOR_GRAPH_FILE}")
    graph = nx.read_graphml(AUTHOR_GRAPH_FILE)
    print(f"Graph: {graph.number_of_nodes()} nodes, {graph.number_of_edges()} edges")

    scored_rows = add_scores(rows, graph)
    write_rows(args.output_file, scored_rows, fieldnames)

    print(f"Saved: {args.output_file}")
    print(f"Formula: combined_score = {KEYWORD_WEIGHT} * keyword_score_norm + {GRAPH_WEIGHT} * author_graph_score")


if __name__ == "__main__":
    main()
